# tasks file for caddy_deploy
- name: Install prerequisites 
  apt:
    pkg:
    - debian-keyring
    - debian-archive-keyring 
    - apt-transport-https
    - curl
  become: yes
- name: Add key for Caddy repo 
  apt_key:
    url: https://dl.cloudsmith.io/public/caddy/stable/gpg.key 
    state: present
    keyring: /usr/share/keyrings/caddy-stable-archive-keyring.gpg
  become: yes
- name: add Caddy repo 
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/caddy-stable-archive-keyring.gpg] https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version main" 
    state: present
    filename: caddy-stable
  become: yes
- name: add Caddy src repo 
  apt_repository:
    repo: "deb-src [signed-by=/usr/share/keyrings/caddy-stable-archive-keyring.gpg] https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version main" 
    state: present
    filename: caddy-stable
  become: yes
- name: Install Caddy webserver 
  apt:
    name: caddy 
    update_cache: yes 
    state: present
  become: yes
- name: Create config file 
  template:
    src: templates/Caddyfile.j2 # Откуда берем 
    dest: /etc/caddy/Caddyfile # Куда кладем
  become: yes
- name: Reload with new config 
  service:
    name: caddy 
    state: reloaded
  become: yes
